config/routes.rb
Rails.application.routes.draw do
  root 'page#index'
  get  'dashboard'                                    => 'dashboard#index'
  get  'dashboard/category/:category_id'              => 'dashboard#document'
  get  'dashboard/generate/:document_id/:template_id' => 'dashboard#generate'
  get  'admin'                                        => 'dashboard#admin'

  resources  :templates,  :except => [:index, :new, :show]
  resources  :fields,     :except => [:index, :new, :show]
  resources  :documents,  :except => [:index]
  resources  :categories, :except => [:index]
  

  scope '/admin' do 
    resources  :users,      :except => [:new, :create, :show]
    
  end



  devise_for :users



  ####
  ####
  ####
  post "test" => 'dashboard#test'
  #get 'products/:id' => 'catalog#view'
end

app/controllers/dashboard_controller.rb
require 'zip'
require 'libreconv'

class DashboardController < ApplicationController
  before_filter :authenticate_user!
  before_action :user
  before_filter :admin, :only => [:admin]
  
  def index
    @fields    = Field.all
  end

  def document
    @current_category = Category.find(params[:category_id])
    @documents = @current_category.documents
  end

  #dub
  def generate
    current_template = @templates.find(params[:template_id])
    current_document = Document.find(params[:document_id])
    
    category = cat_main(current_document.category)
    perm = Permission.find_by(:user_id => current_user.id, :category_id => category)
    if current_user.admin? || !perm.nil? && perm.status == 5    
      path   = "word/document.xml"
      fields = current_template.template_fields.map {|i| [i.field.code, i.val]} 

      zf = Zip::File.new("public/templates/#{current_document.path}.#{current_document.extension}")
      buffer = Zip::OutputStream.write_buffer do |out|
        zf.entries.each do |e|
          if e.ftype == :directory
            out.put_next_entry(e.name)
          else
            if e.name == path
              out.put_next_entry(e.name)
              xml = e.get_input_stream.read.force_encoding("UTF-8")
              fields.concat(dynamic_fields).each do |field|
                xml.gsub!("{#{field[0]}}","#{field[1]}")
              end

              out.write xml
            else
              out.put_next_entry(e.name)
              out.write e.get_input_stream.read
            end
          end
        end
      end

      hash     = Digest::SHA256.hexdigest(Time.new.to_s + rand.to_s)
      filepath = "tmp/documents/#{hash}"
      File.open(filepath, "wb") {|f| f.write(buffer.string) } 
      Libreconv.convert(filepath, "#{filepath}.pdf")
      send_file("#{filepath}.pdf", :filename => "#{current_document.name}.pdf")
    else
      redirect_to dashboard_path, notice: t('not_permssion')
    end
  end

  def admin
    @fields = Field.all
  end 

  private
    def user
      @category   = Category.root
      @categories = Category.all.map{|i| (i.name != 'root' ? [i.name, i.id] : [t("chose_category"), 0])} 
      @templates  = current_user.templates
    end

    def dynamic_fields
      [['year', Time.now.year.to_s], ['copyng_free', "Созданно в генераторе документов пробное использование"]]
    end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_add_category.html.haml
=form_for Category.new do |f|
  .form-group
    = f.text_field :name, :class=> 'form-control', :placeholder => t('name')
  .form-group
    = f.select(:parent_id, Category.all.map{|i| (i.name != 'root' ? [i.name, i.id] : [t("main"), 1])} , {},{:class => 'form-control'})
  .actions
    = f.submit t('save', :default=> "Save"), :class=> 'btn btn-primary form-control'

app/views/dashboard/_admin_category.html.haml
-if perm?(admin_category, 5) || admin?
  %li
    =link_to "#category#{admin_category.id}", :class => 'dropdown-toggle category', :data=> {:toggle=>'dropdown', :toggle=>"collapse", :parent=> "#accordion" } do
      =admin_category.name
      -if admin_category.documents.count != 0  
        %span.caret

    =link_to edit_category_path(admin_category.id), :class => 'category-link' do
      %i.glyphicon.glyphicon-pencil

    =link_to category_path(admin_category.id), :class => 'category-link', :data => {:confirm => t('are_you_sure', :default => 'Are you sure?')}, :method => :delete do
      %i.glyphicon.glyphicon-trash

    -if admin_category.documents.count != 0
      %ul.panel-collapse.collapse.nav{:id => "category#{admin_category.id}"}
        -admin_category.documents.each do |doc|
          %li
            =link_to document_path(doc.id), :class => "category" do
              =doc.name

            =link_to edit_document_path(doc.id), :class => 'category-link' do
              %i.glyphicon.glyphicon-pencil
            =link_to document_path(doc.id), :class => "category-link", :data => {:confirm => t('are_you_sure', :default => 'Are you sure?')}, :method => :delete do
              %i.glyphicon.glyphicon-trash 


  -unless admin_category.children.empty?
    %ul.nav.nav-list.tree
      =render :partial => "dashboard/admin_category", :collection => admin_category.children

app/views/dashboard/_category.html.haml
-if perm?(category, 5) || admin?
  -if category.documents.count != 0
    %li 
      =link_to category_path(category.id) do
        =category.name
  -else
    %li.disabled
      =link_to "#" do
        =category.name 

  -unless category.children.empty?
    %ul.nav.nav-list.tree
      =render :partial => "dashboard/category", :collection => category.children

app/views/dashboard/_document.html.haml
%li
  =document.name

  =link_to document_path(document.id), :data => {:confirm => t('are_you_sure', :default => 'Are you sure?')}, :method => :delete do
    %i.glyphicon.glyphicon-trash    

  %ul
    -@templates.each do |t|
      %li= link_to t.name,  dashboard_path + "/generate/#{document.id}/#{t.id}"

  %iframe{frameborder: "0", src: "http://docs.google.com/gview?url=http://#{request.host}/preview/#{document.path}.pdf&embedded=true", style: "width:600px; height:500px;"}

app/views/dashboard/_field.html.haml
%tr
  %td
    =link_to edit_field_path(field.id) do
      = field.name
    -unless field.about.nil? || field.about.empty? 
      %i.glyphicon.glyphicon-question-sign.tag-tooltip{:title => field.about}      
  %td=field.code.gsub(" ", "▉")
  %td
    =link_to field_path(field.id), :data => {:confirm => t('are_you_sure', :default => 'Are you sure?')}, :method => :delete do
      %i.glyphicon.glyphicon-trash

app/views/dashboard/_form_field.html.haml
//ddd
%tr
=form_for :field, :url => fields_path  do |f|
  %td
    =f.text_field :name,  :class => "form-control",      :placeholder => t('activerecord.attributes.field.name',  :default => 'Name')
    =f.text_field :code,  :class => "form-control",      :placeholder => t('activerecord.attributes.field.code',  :default => 'Code')
  %td
    =f.text_area  :about, :class => "form-control area", :placeholder => t('activerecord.attributes.field.about', :default => 'About')
  %td
    =f.submit t('save', :default => "Save"), :class => "form-control btn btn-primary"

app/views/dashboard/_form_template.html.haml
%tr
=form_for :template, :url => templates_path do |f|
  %td
    =f.text_field :name,  :class => "form-control",      :placeholder => t('activerecord.attributes.template.name')
  %td
    =f.text_area  :about, :class => "form-control area", :placeholder => t('activerecord.attributes.template.about')
  %td{:colspan => 3}
    =f.submit t('add', :default => "Add"), :class => "form-control btn btn-primary"

app/views/dashboard/_modal.html.haml
#myModal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", type: "button"}
          %span{"aria-hidden" => "true"} &#215;
          %span.sr-only=t('close')
        %h4.modal-title=t('document_view')
      .modal-body
        %iframe#gpdf{frameborder: "0", src: "", width: "100%"}
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", type: "button"}=t('close')
        %a.btn.btn-primary#dpdf{:href=>"#"}
          %span.glyphicon.glyphicon-cloud-download
          =t('download')

app/views/dashboard/_template.html.haml
%tr
  %td
    =link_to edit_template_path(template.id) do
      =template.name
    -unless template.about.nil? || template.about.empty?
      %i.glyphicon.glyphicon-question-sign.tag-tooltip{:title => template.about}
  %td
  %td=template.template_fields.count
  %td
  %td
    =link_to template_path(template.id), :data => {:confirm => t('are_you_sure', :default => 'Are you sure?')}, :method => :delete do
      %i.glyphicon.glyphicon-trash

app/views/dashboard/admin.html.haml
.row
  .col-md-4
    .well
      %h2= t 'categories'
      %ul.nav
        =render :partial => "admin_category", :collection => @category.children

    .well
      %h3=t 'add_category'
      =render :partial => 'add_category'

    .well
      %h3#file= t 'uploads'
      %p#file_status
        &nbsp;
      = form_for :documents, :url => documents_path do |f|
        .form-group
          = f.text_field :name, :class => 'form-control change', :placeholder => t('name')
        .form-group
          = f.select(:category, @categories, {},{:class => 'form-control change'})
      #fileupload.upload
        %p=t 'drag_drop'
      .progress#progress


  .col-md-8
    %h3= t 'all_fields'
    %table.table
      %tr.danger
        %th= t 'name'
        %th= t 'code'
        %th
      =render :partial => "field", :collection => @fields
      =render :partial => "form_field"

app/views/dashboard/document.html.haml
.row
  .col-md-8
    -if @documents.count == 0
      %h2= t 'no_document'
    -elsif
      %h2= t 'document'
    -else 
      %h2= t 'documents'
    %ul
      =render :partial => "document", :collection => @documents
  .col-md-4.well
    %h2= t 'categories'
    =render :partial => "category", :collection => @category.children

app/views/dashboard/index.html.haml
.row
  .col-md-12
    -if @templates.count == 1
      %h2= t 'template'
    -else
      %h2= t 'templates'
    %table.table
      %tr.info
        %th= t 'name'
        %th
        %th= t 'fields'
        %th
        %th
      =render :partial => "template", :collection => @templates
      =render :partial => "form_template"
      
    