config/routes.rb
Rails.application.routes.draw do
  root 'page#index'
  get  'dashboard'                                    => 'dashboard#index'
  get  'dashboard/category/:category_id'              => 'dashboard#document'
  get  'dashboard/generate/:document_id/:template_id' => 'dashboard#generate'
  get  'admin'                                        => 'dashboard#admin'

  resources  :templates,  :except => [:index, :new, :show]
  resources  :fields,     :except => [:index, :new, :show]
  resources  :documents,  :except => [:index]
  resources  :categories, :except => [:index]
  

  scope '/admin' do 
    resources  :users,      :except => [:new, :create, :show]
    
  end



  devise_for :users



  ####
  ####
  ####
  post "test" => 'dashboard#test'
  #get 'products/:id' => 'catalog#view'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many   :children,   class_name: "Category", foreign_key: "parent_id", dependent: :destroy
  belongs_to :parent,     class_name: "Category"

  has_many :documents,   dependent: :destroy
  has_many :permissions, dependent: :destroy 

  scope :root, -> { find_by(:parent_id => -1) }


  validates :name,  :presence => true, 
                    :length => {:minimum => 3, :maximum => 128}

  validates :parent_id,  :presence => true,
                    :inclusion => { :in => 1..10000, :message => 'chose_parent_category' }


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  before_filter :admin
  
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @documents = @category.documents
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_path, notice: t('category_added') }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_path, notice: t('category_updated') }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_path, notice: t('category_destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
      @root_cat = Category.root 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :parent_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, t('name')
    = f.text_field :name, :class=> 'form-control'
  .form-group
    = f.label :parent_id, t('parent')
    = f.select(:parent_id, Category.all.map{|i| (i.name != 'root' ? [i.name, i.id] : [t("main"), 1])} , {},{:class => 'form-control'})
  .actions
    = f.submit t('save', :default=> "Save"), :class=> 'btn btn-primary form-control'

app/views/categories/edit.html.haml
%h1= t('editing_category')

= render 'form'

app/views/categories/new.html.haml
%h1=t('new_category')

= render 'form'

app/views/categories/show.html.haml
.row
  .col-md-12
    %h1
      =@category.name
      %small
        =t('count')
        \–
        =@documents.count

    //%ul.nav.nav-pills
    //-@templates.each do |t|
    //%li
    //= link_to dashboard_path + "/generate/#{@document.id}/#{t.id}" do
    //=t.name 
    //%i.glyphicon.glyphicon-download

.row
  .col-md-4.well
    %h2= t 'categories'
    %ul.nav.nav-list
      =render :partial => "dashboard/category", :collection => @root_cat.children
  //%iframe#google-iframe{frameborder: "0", src: "http://docs.google.com/gview?url=http://#{request.host}/preview/#{@document.path}.pdf&embedded=true"}
  .col-md-8
    %table.table.table-hover
      %tr
        %th=t('name')
        %th{:width=>'20px'}
        %th{:width=>'20px'}
        %th{:width=>'20px'}

      - @documents.each do |document|
        %tr
          %td= document.name
          %td
            = link_to "http://#{request.host}/preview/#{document.path}.pdf", :class => "openBtn", :alt=> t('view', :default=>"View") do
              %span.glyphicon.glyphicon-list-alt{:id=>"view_#{document.id}"}
          %td
            = link_to edit_document_path(document), :alt=>t('edit') do
              %span.glyphicon.glyphicon-pencil
          %td
            = link_to document, :method => :delete, :data => { :confirm => 'Are you sure?' }, :alt=>t('destroy') do
              %span.glyphicon.glyphicon-trash

=render :partial => "dashboard/modal"